### PR TITLE
Save generated Arduino code locally

### PR DESCRIPTION
**Pull request by stevoleeto**
Adds a new button to the top of the file called, "Save Arduino Code".
Clicking this asks the user to name the file, after which it downloads as an .ino file ready to opened in Arduino.

screen shot 2015-07-24 at 8 04 59 pm
screen shot 2015-07-24 at 8 05 13 pm
screen shot 2015-07-24 at 8 07 15 pm

### CODE REVIEW

**Comment by carlosperate** [comment]
Good idea! For consistency maybe the same prompt could be added to the save xml button?

**Comment by stevoleeto** [comment]
@carlosperate doing this right now actually :)

**Comment by carlosperate** [comment]
Added some comments to the other pull request, the same apply here.

**Comment by gasolin** [comment]
thanks!

**Pull request merged**
